// A broad, real list of world countries for the "worldwide" marquee on the
// landing/pricing pages. Flags are rendered as native Unicode flag emoji
// (regional indicator symbols) — not logos or downloaded images — so there
// is nothing to license, host, or attribute: every OS/browser renders the
// real flag for the ISO code itself.
//
// Names are given in both languages directly (not routed through the
// src/lib/locales/*.ts dictionaries) since this list is data, not UI copy,
// and keeping ~100 country names in perfect fr/en key parity there would
// bloat the locale files for no translation benefit — the country name
// itself doesn't need pluralization/interpolation like real UI strings do.

export type Country = { code: string; en: string; fr: string };

// Converts an ISO 3166-1 alpha-2 code to its flag emoji via regional
// indicator symbols, so we only maintain the code + names below.
export function flagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

export const COUNTRIES: Country[] = [
  { code: 'NG', en: 'Nigeria', fr: 'Nigéria' },
  { code: 'EG', en: 'Egypt', fr: 'Égypte' },
  { code: 'ZA', en: 'South Africa', fr: 'Afrique du Sud' },
  { code: 'KE', en: 'Kenya', fr: 'Kenya' },
  { code: 'GH', en: 'Ghana', fr: 'Ghana' },
  { code: 'CI', en: "Côte d'Ivoire", fr: "Côte d'Ivoire" },
  { code: 'SN', en: 'Senegal', fr: 'Sénégal' },
  { code: 'CM', en: 'Cameroon', fr: 'Cameroun' },
  { code: 'ML', en: 'Mali', fr: 'Mali' },
  { code: 'BF', en: 'Burkina Faso', fr: 'Burkina Faso' },
  { code: 'BJ', en: 'Benin', fr: 'Bénin' },
  { code: 'TG', en: 'Togo', fr: 'Togo' },
  { code: 'NE', en: 'Niger', fr: 'Niger' },
  { code: 'GN', en: 'Guinea', fr: 'Guinée' },
  { code: 'GA', en: 'Gabon', fr: 'Gabon' },
  { code: 'CD', en: 'DR Congo', fr: 'RD Congo' },
  { code: 'CG', en: 'Congo', fr: 'Congo' },
  { code: 'TD', en: 'Chad', fr: 'Tchad' },
  { code: 'CF', en: 'Central African Rep.', fr: 'Rép. Centrafricaine' },
  { code: 'TZ', en: 'Tanzania', fr: 'Tanzanie' },
  { code: 'UG', en: 'Uganda', fr: 'Ouganda' },
  { code: 'RW', en: 'Rwanda', fr: 'Rwanda' },
  { code: 'ET', en: 'Ethiopia', fr: 'Éthiopie' },
  { code: 'ZM', en: 'Zambia', fr: 'Zambie' },
  { code: 'ZW', en: 'Zimbabwe', fr: 'Zimbabwe' },
  { code: 'MZ', en: 'Mozambique', fr: 'Mozambique' },
  { code: 'AO', en: 'Angola', fr: 'Angola' },
  { code: 'NA', en: 'Namibia', fr: 'Namibie' },
  { code: 'BW', en: 'Botswana', fr: 'Botswana' },
  { code: 'MW', en: 'Malawi', fr: 'Malawi' },
  { code: 'MA', en: 'Morocco', fr: 'Maroc' },
  { code: 'DZ', en: 'Algeria', fr: 'Algérie' },
  { code: 'TN', en: 'Tunisia', fr: 'Tunisie' },
  { code: 'LY', en: 'Libya', fr: 'Libye' },
  { code: 'SD', en: 'Sudan', fr: 'Soudan' },
  { code: 'MG', en: 'Madagascar', fr: 'Madagascar' },
  { code: 'MU', en: 'Mauritius', fr: 'Maurice' },
  { code: 'BI', en: 'Burundi', fr: 'Burundi' },
  { code: 'SL', en: 'Sierra Leone', fr: 'Sierra Leone' },
  { code: 'LR', en: 'Liberia', fr: 'Libéria' },
  { code: 'GM', en: 'Gambia', fr: 'Gambie' },
  { code: 'GW', en: 'Guinea-Bissau', fr: 'Guinée-Bissau' },
  { code: 'MR', en: 'Mauritania', fr: 'Mauritanie' },
  { code: 'DJ', en: 'Djibouti', fr: 'Djibouti' },
  { code: 'SO', en: 'Somalia', fr: 'Somalie' },
  { code: 'SS', en: 'South Sudan', fr: 'Soudan du Sud' },
  { code: 'ER', en: 'Eritrea', fr: 'Érythrée' },
  { code: 'SZ', en: 'Eswatini', fr: 'Eswatini' },
  { code: 'LS', en: 'Lesotho', fr: 'Lesotho' },
  { code: 'CV', en: 'Cabo Verde', fr: 'Cap-Vert' },
  { code: 'AE', en: 'United Arab Emirates', fr: 'Émirats Arabes Unis' },
  { code: 'SA', en: 'Saudi Arabia', fr: 'Arabie Saoudite' },
  { code: 'QA', en: 'Qatar', fr: 'Qatar' },
  { code: 'KW', en: 'Kuwait', fr: 'Koweït' },
  { code: 'BH', en: 'Bahrain', fr: 'Bahreïn' },
  { code: 'OM', en: 'Oman', fr: 'Oman' },
  { code: 'JO', en: 'Jordan', fr: 'Jordanie' },
  { code: 'LB', en: 'Lebanon', fr: 'Liban' },
  { code: 'IQ', en: 'Iraq', fr: 'Irak' },
  { code: 'IL', en: 'Israel', fr: 'Israël' },
  { code: 'TR', en: 'Turkey', fr: 'Turquie' },
  { code: 'IN', en: 'India', fr: 'Inde' },
  { code: 'PK', en: 'Pakistan', fr: 'Pakistan' },
  { code: 'BD', en: 'Bangladesh', fr: 'Bangladesh' },
  { code: 'CN', en: 'China', fr: 'Chine' },
  { code: 'JP', en: 'Japan', fr: 'Japon' },
  { code: 'KR', en: 'South Korea', fr: 'Corée du Sud' },
  { code: 'ID', en: 'Indonesia', fr: 'Indonésie' },
  { code: 'MY', en: 'Malaysia', fr: 'Malaisie' },
  { code: 'SG', en: 'Singapore', fr: 'Singapour' },
  { code: 'TH', en: 'Thailand', fr: 'Thaïlande' },
  { code: 'VN', en: 'Vietnam', fr: 'Viêt Nam' },
  { code: 'PH', en: 'Philippines', fr: 'Philippines' },
  { code: 'GB', en: 'United Kingdom', fr: 'Royaume-Uni' },
  { code: 'FR', en: 'France', fr: 'France' },
  { code: 'DE', en: 'Germany', fr: 'Allemagne' },
  { code: 'ES', en: 'Spain', fr: 'Espagne' },
  { code: 'PT', en: 'Portugal', fr: 'Portugal' },
  { code: 'IT', en: 'Italy', fr: 'Italie' },
  { code: 'NL', en: 'Netherlands', fr: 'Pays-Bas' },
  { code: 'BE', en: 'Belgium', fr: 'Belgique' },
  { code: 'CH', en: 'Switzerland', fr: 'Suisse' },
  { code: 'SE', en: 'Sweden', fr: 'Suède' },
  { code: 'NO', en: 'Norway', fr: 'Norvège' },
  { code: 'IE', en: 'Ireland', fr: 'Irlande' },
  { code: 'PL', en: 'Poland', fr: 'Pologne' },
  { code: 'GR', en: 'Greece', fr: 'Grèce' },
  { code: 'US', en: 'United States', fr: 'États-Unis' },
  { code: 'CA', en: 'Canada', fr: 'Canada' },
  { code: 'MX', en: 'Mexico', fr: 'Mexique' },
  { code: 'BR', en: 'Brazil', fr: 'Brésil' },
  { code: 'AR', en: 'Argentina', fr: 'Argentine' },
  { code: 'CO', en: 'Colombia', fr: 'Colombie' },
  { code: 'CL', en: 'Chile', fr: 'Chili' },
  { code: 'PE', en: 'Peru', fr: 'Pérou' },
  { code: 'HT', en: 'Haiti', fr: 'Haïti' },
  { code: 'DO', en: 'Dominican Rep.', fr: 'Rép. Dominicaine' },
  { code: 'JM', en: 'Jamaica', fr: 'Jamaïque' },
  { code: 'AU', en: 'Australia', fr: 'Australie' },
  { code: 'NZ', en: 'New Zealand', fr: 'Nouvelle-Zélande' },
];
