// Localisation mondiale — pays, devises, régions, moyens de paiement.
// L'Afrique reste enrichie en détail (régions/villes/mobile money précis,
// c'est le marché historique du produit) ; le reste du monde est couvert
// via des données ISO (nom FR, devise, indicatif, capitale, continent) afin
// que tous les pays soient sélectionnables, avec la même logique de
// repli déjà en place dans l'UI (région/ville en saisie libre si absentes).

export type CountryInfo = {
  code: string;
  name: string;
  currency: string;
  dialCode: string;
  regions: string[];
  cities: string[];
  mobileMoney: string[];
  languages: string[];
  continent: 'Africa' | 'Asia' | 'Middle East' | 'Europe' | 'North America' | 'Central America & Caribbean' | 'South America' | 'Oceania';
};

export const COUNTRIES: CountryInfo[] = [
  { code: 'CM', name: 'Cameroun', currency: 'XAF', dialCode: '+237', regions: ['Centre', 'Littoral', 'Ouest', 'Sud-Ouest', 'Nord-Ouest', 'Sud', 'Est', 'Adamaoua', 'Nord', 'Extrême-Nord'], cities: ['Douala', 'Yaoundé', 'Bafoussam', 'Bamenda', 'Garoua', 'Maroua', 'Soa', 'Kribi', 'Limbé', 'Ebolowa'], mobileMoney: ['Orange Money', 'MTN Mobile Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'CI', name: "Côte d'Ivoire", currency: 'XOF', dialCode: '+225', regions: ['Abidjan', 'Lagunes', 'Comoé', 'Sud-Comoé', 'Gôh-Djiboua', 'Bas-Sassandra', 'Haut-Sassandra'], cities: ['Abidjan', 'Bouaké', 'Yamoussoukro', 'San-Pédro', 'Korhogo', 'Daloa'], mobileMoney: ['Orange Money', 'MTN Mobile Money', 'Moov Money', 'Wave'], languages: ['fr'] , continent: 'Africa' },
  { code: 'SN', name: 'Sénégal', currency: 'XOF', dialCode: '+221', regions: ['Dakar', 'Thiès', 'Diourbel', 'Saint-Louis', 'Kaolack', 'Ziguinchor'], cities: ['Dakar', 'Thiès', 'Saint-Louis', 'Kaolack', 'Touba', 'Ziguinchor'], mobileMoney: ['Orange Money', 'Wave', 'Free Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', dialCode: '+234', regions: ['Lagos', 'Abuja FCT', 'Rivers', 'Kano', 'Oyo', 'Kaduna', 'Enugu'], cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna'], mobileMoney: ['MTN MoMo', 'OPay', 'Paga'], languages: ['en'] , continent: 'Africa' },
  { code: 'KE', name: 'Kenya', currency: 'KES', dialCode: '+254', regions: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'], cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika'], mobileMoney: ['M-Pesa', 'Airtel Money', 'T-Kash'], languages: ['en', 'sw'] , continent: 'Africa' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', dialCode: '+233', regions: ['Greater Accra', 'Ashanti', 'Western', 'Central', 'Eastern', 'Northern'], cities: ['Accra', 'Kumasi', 'Takoradi', 'Cape Coast', 'Tamale', 'Tema'], mobileMoney: ['MTN MoMo', 'Vodafone Cash', 'AirtelTigo Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'TZ', name: 'Tanzanie', currency: 'TZS', dialCode: '+255', regions: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza', 'Zanzibar'], cities: ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mwanza', 'Zanzibar City'], mobileMoney: ['M-Pesa', 'Tigo Pesa', 'Airtel Money', 'Halopesa'], languages: ['en', 'sw'] , continent: 'Africa' },
  { code: 'UG', name: 'Ouganda', currency: 'UGX', dialCode: '+256', regions: ['Central', 'Eastern', 'Northern', 'Western'], cities: ['Kampala', 'Entebbe', 'Jinja', 'Gulu', 'Mbarara'], mobileMoney: ['MTN MoMo', 'Airtel Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'ET', name: 'Éthiopie', currency: 'ETB', dialCode: '+251', regions: ['Addis Ababa', 'Oromia', 'Amhara', 'Tigray', 'Sidama'], cities: ['Addis Ababa', 'Dire Dawa', 'Adama', 'Gondar', 'Hawassa'], mobileMoney: ['Telebirr', 'CBE Birr'], languages: ['en', 'am'] , continent: 'Africa' },
  { code: 'EG', name: 'Égypte', currency: 'EGP', dialCode: '+20', regions: ['Le Caire', 'Alexandrie', 'Gizeh', 'Assouan', 'Louxor'], cities: ['Le Caire', 'Alexandrie', 'Gizeh', 'Assouan', 'Louxor', 'Port-Saïd'], mobileMoney: ['Vodafone Cash', 'Etisalat Cash'], languages: ['ar', 'en'] , continent: 'Africa' },
  { code: 'MA', name: 'Maroc', currency: 'MAD', dialCode: '+212', regions: ['Casablanca-Settat', 'Rabat-Salé-Kénitra', 'Marrakech-Safi', 'Fès-Meknès', 'Tanger-Tétouan'], cities: ['Casablanca', 'Rabat', 'Marrakech', 'Fès', 'Tanger', 'Agadir'], mobileMoney: ['Inwi Money', 'Cash Plus'], languages: ['ar', 'fr'] , continent: 'Africa' },
  { code: 'DZ', name: 'Algérie', currency: 'DZD', dialCode: '+213', regions: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Sétif'], cities: ['Alger', 'Oran', 'Constantine', 'Annaba', 'Sétif', 'Blida'], mobileMoney: ['Edahabia', 'BaridiMob'], languages: ['ar', 'fr'] , continent: 'Africa' },
  { code: 'ZA', name: 'Afrique du Sud', currency: 'ZAR', dialCode: '+27', regions: ['Gauteng', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Free State'], cities: ['Johannesburg', 'Le Cap', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein'], mobileMoney: ['SnapScan', 'Zapper'], languages: ['en'] , continent: 'Africa' },
  { code: 'CD', name: 'RD Congo', currency: 'CDF', dialCode: '+243', regions: ['Kinshasa', 'Kongo Central', 'Haut-Katanga', 'Nord-Kivu', 'Sud-Kivu'], cities: ['Kinshasa', 'Lubumbashi', 'Goma', 'Bukavu', 'Mbuji-Mayi', 'Kisangani'], mobileMoney: ['M-Pesa', 'Orange Money', 'Airtel Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'CG', name: 'Congo', currency: 'XAF', dialCode: '+242', regions: ['Brazzaville', 'Pointe-Noire', 'Cuvette', 'Likouala', 'Sangha'], cities: ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Owando', 'Impfondo'], mobileMoney: ['Airtel Money', 'MTN Mobile Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'GA', name: 'Gabon', currency: 'XAF', dialCode: '+241', regions: ['Estuaire', 'Haut-Ogooué', 'Moyen-Ogooué', 'Ngounié'], cities: ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'], mobileMoney: ['Airtel Money', 'Moov Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'ML', name: 'Mali', currency: 'XOF', dialCode: '+223', regions: ['Bamako', 'Kayes', 'Sikasso', 'Ségou', 'Mopti'], cities: ['Bamako', 'Sikasso', 'Ségou', 'Kayes', 'Mopti', 'Tombouctou'], mobileMoney: ['Orange Money', 'Moov Money', 'Wave'], languages: ['fr'] , continent: 'Africa' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', dialCode: '+226', regions: ['Centre', 'Hauts-Bassins', 'Boucle du Mouhoun', 'Nord', 'Est'], cities: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya'], mobileMoney: ['Orange Money', 'Moov Money', 'Coris Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'BJ', name: 'Bénin', currency: 'XOF', dialCode: '+229', regions: ['Littoral', 'Atlantique', 'Ouémé', 'Zou', 'Mono'], cities: ['Cotonou', 'Porto-Novo', 'Parakou', 'Abomey', 'Natitingou'], mobileMoney: ['MTN MoMo', 'Moov Money', 'Celtiis Cash'], languages: ['fr'] , continent: 'Africa' },
  { code: 'TG', name: 'Togo', currency: 'XOF', dialCode: '+228', regions: ['Maritime', 'Plateaux', 'Centrale', 'Kara', 'Savanes'], cities: ['Lomé', 'Sokodé', 'Kara', 'Atakpamé', 'Dapaong'], mobileMoney: ['Moov Money', 'Togo Cel', 'TMoney'], languages: ['fr'] , continent: 'Africa' },
  { code: 'NE', name: 'Niger', currency: 'XOF', dialCode: '+227', regions: ['Niamey', 'Maradi', 'Zinder', 'Tillabéri', 'Diffa'], cities: ['Niamey', 'Maradi', 'Zinder', 'Agadez', 'Diffa'], mobileMoney: ['Airtel Money', 'Moov Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'GN', name: 'Guinée', currency: 'GNF', dialCode: '+224', regions: ['Conakry', 'Kindia', 'Boké', 'Kankan', 'Nzérékoré'], cities: ['Conakry', 'Kankan', 'Kindia', 'Boké', 'Nzérékoré'], mobileMoney: ['Orange Money', 'MTN Mobile Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLL', dialCode: '+232', regions: ['Western Area', 'Northern', 'Southern', 'Eastern'], cities: ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu'], mobileMoney: ['Orange Money', 'Africell Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', dialCode: '+231', regions: ['Montserrado', 'Nimba', 'Bong', 'Grand Bassa'], cities: ['Monrovia', 'Gbarnga', 'Buchanan', 'Ganta', 'Kakata'], mobileMoney: ['Lonestar Cell Money', 'Orange Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', dialCode: '+250', regions: ['Kigali', 'Nord', 'Sud', 'Est', 'Ouest'], cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi'], mobileMoney: ['MTN MoMo', 'Airtel Money'], languages: ['en', 'fr', 'rw'] , continent: 'Africa' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', dialCode: '+257', regions: ['Bujumbura', 'Bubanza', 'Bururi', 'Gitega'], cities: ['Bujumbura', 'Gitega', 'Ngozi', 'Muyinga', 'Rumonge'], mobileMoney: ['Lumicash', 'Ecobank Mobile'], languages: ['fr', 'en'] , continent: 'Africa' },
  { code: 'MW', name: 'Malawi', currency: 'MWK', dialCode: '+265', regions: ['Central', 'Southern', 'Northern'], cities: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'], mobileMoney: ['Airtel Money', 'TNM Mpamba'], languages: ['en'] , continent: 'Africa' },
  { code: 'ZM', name: 'Zambie', currency: 'ZMW', dialCode: '+260', regions: ['Lusaka', 'Copperbelt', 'Southern', 'Northern'], cities: ['Lusaka', 'Ndola', 'Kitwe', 'Kabwe', 'Livingstone'], mobileMoney: ['Airtel Money', 'MTN Mobile Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', dialCode: '+263', regions: ['Harare', 'Bulawayo', 'Manicaland', 'Mashonaland'], cities: ['Harare', 'Bulawayo', 'Mutare', 'Gweru', 'Masvingo'], mobileMoney: ['EcoCash', 'OneMoney'], languages: ['en'] , continent: 'Africa' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', dialCode: '+258', regions: ['Maputo', 'Gaza', 'Sofala', 'Nampula'], cities: ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'], mobileMoney: ['mPesa', 'e-Mola'], languages: ['pt', 'en'] , continent: 'Africa' },
  { code: 'AO', name: 'Angola', currency: 'AOA', dialCode: '+244', regions: ['Luanda', 'Benguela', 'Huambo', 'Huíla'], cities: ['Luanda', 'Huambo', 'Benguela', 'Lobito', 'Lubango'], mobileMoney: ['Unitel Money', 'Multicaixa Express'], languages: ['pt'] , continent: 'Africa' },
  { code: 'SD', name: 'Soudan', currency: 'SDG', dialCode: '+249', regions: ['Khartoum', 'Gezira', 'Kordofan', 'Darfur'], cities: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala', 'El Obeid'], mobileMoney: ['Zain Cash', 'MTN Mobile Money'], languages: ['ar', 'en'] , continent: 'Africa' },
  { code: 'TN', name: 'Tunisie', currency: 'TND', dialCode: '+216', regions: ['Tunis', 'Sfax', 'Sousse', 'Nabeul', 'Ariana'], cities: ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte'], mobileMoney: ['D17', 'PayDya'], languages: ['ar', 'fr'] , continent: 'Africa' },
  { code: 'LY', name: 'Libye', currency: 'LYD', dialCode: '+218', regions: ['Tripoli', 'Benghazi', 'Misrata', 'Zliten'], cities: ['Tripoli', 'Benghazi', 'Misrata', 'Zawiya', 'Zliten'], mobileMoney: ['Madfouna'], languages: ['ar'] , continent: 'Africa' },
  { code: 'MR', name: 'Mauritanie', currency: 'MRU', dialCode: '+222', regions: ['Nouakchott', 'Hodh Ech Chargui', 'Trarza', 'Brakna'], cities: ['Nouakchott', 'Nouadhibou', 'Kaédi', 'Rosso', 'Atar'], mobileMoney: ['Bankily', 'Masrifi'], languages: ['ar', 'fr'] , continent: 'Africa' },
  { code: 'GM', name: 'Gambie', currency: 'GMD', dialCode: '+220', regions: ['Banjul', 'Western', 'Lower River', 'Central River'], cities: ['Banjul', 'Serekunda', 'Brikama', 'Farafenni'], mobileMoney: ['Wari', 'Africell Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'GW', name: 'Guinée-Bissau', currency: 'XOF', dialCode: '+245', regions: ['Bissau', 'Bolama', 'Cacheu', 'Gabu'], cities: ['Bissau', 'Bafatá', 'Gabú', 'Cacheu'], mobileMoney: ['Orange Money', 'MTN Mobile Money'], languages: ['pt', 'fr'] , continent: 'Africa' },
  { code: 'CV', name: 'Cap-Vert', currency: 'CVE', dialCode: '+238', regions: ['Santiago', 'São Vicente', 'Santo Antão', 'Fogo'], cities: ['Praia', 'Mindelo', 'Assomada', 'Espargos'], mobileMoney: ['Unitel T\'+'], languages: ['pt'] , continent: 'Africa' },
  { code: 'KM', name: 'Comores', currency: 'KMF', dialCode: '+269', regions: ['Grande Comore', 'Anjouan', 'Mohéli'], cities: ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni'], mobileMoney: ['Mvola'], languages: ['fr', 'ar'] , continent: 'Africa' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', dialCode: '+248', regions: ['Mahé', 'Praslin', 'La Digue'], cities: ['Victoria', 'Anse Royale', 'Beau Vallon'], mobileMoney: ['SeyPay'], languages: ['en', 'fr'] , continent: 'Africa' },
  { code: 'MU', name: 'Maurice', currency: 'MUR', dialCode: '+230', regions: ['Port-Louis', 'Pamplemousses', 'Plaines Wilhems', 'Flacq'], cities: ['Port-Louis', 'Curepipe', 'Vacoas', 'Quatre Bornes'], mobileMoney: ['My.t Money', 'Mauritius Telecom Money'], languages: ['en', 'fr'] , continent: 'Africa' },
  { code: 'ST', name: 'Sao Tomé et Príncipe', currency: 'STN', dialCode: '+239', regions: ['Sao Tomé', 'Príncipe'], cities: ['Sao Tomé', 'Santana', 'Trindade', 'Neves'], mobileMoney: ['Unitel Money'], languages: ['pt'] , continent: 'Africa' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', dialCode: '+253', regions: ['Djibouti', 'Arta', 'Dikhil', 'Ali Sabieh'], cities: ['Djibouti', 'Ali Sabieh', 'Dikhil', 'Tadjourah'], mobileMoney: ['Evci', 'Mobile Cash'], languages: ['fr', 'ar'] , continent: 'Africa' },
  { code: 'SO', name: 'Somalie', currency: 'SOS', dialCode: '+252', regions: ['Banadir', 'Bakool', 'Bari', 'Galguduud'], cities: ['Mogadiscio', 'Hargeisa', 'Kismayo', 'Baidoa', 'Bossaso'], mobileMoney: ['EVC Plus', 'Sahal', 'Hormuud'], languages: ['so', 'en'] , continent: 'Africa' },
  { code: 'SS', name: 'Soudan du Sud', currency: 'SSP', dialCode: '+211', regions: ['Central Equatoria', 'Jonglei', 'Lakes', 'Unity'], cities: ['Juba', 'Wau', 'Malakal', 'Yei', 'Bor'], mobileMoney: ['mCash', 'Ezee Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'ER', name: 'Érythrée', currency: 'ERN', dialCode: '+291', regions: ['Maekel', 'Anseba', 'Gash-Barka', 'Debub'], cities: ['Asmara', 'Keren', 'Assab', 'Massawa', 'Mendefera'], mobileMoney: ['Hiber Mobile Money'], languages: ['ar', 'en'] , continent: 'Africa' },
  { code: 'CF', name: 'Centrafrique', currency: 'XAF', dialCode: '+236', regions: ['Bangui', 'Lobaye', 'Ombella-Mpoko', 'Haut-Mbomou'], cities: ['Bangui', 'Bimbo', 'Berbérati', 'Bouar', 'Kaga-Bandoro'], mobileMoney: ['Airtel Money', 'Orange Money'], languages: ['fr'] , continent: 'Africa' },
  { code: 'TD', name: 'Tchad', currency: 'XAF', dialCode: '+235', regions: ['N\'Djamena', 'Hadjer-Lamis', 'Logone Occidental', 'Mayo-Kebbi'], cities: ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kelo'], mobileMoney: ['Airtel Money', 'Moov Money'], languages: ['fr', 'ar'] , continent: 'Africa' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', dialCode: '+266', regions: ['Maseru', 'Berea', 'Mafeteng', 'Leribe'], cities: ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse'], mobileMoney: ['Econet EcoCash', 'MPesa'], languages: ['en'] , continent: 'Africa' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', dialCode: '+268', regions: ['Hhohho', 'Manzini', 'Shiselweni', 'Lubombo'], cities: ['Mbabane', 'Manzini', 'Siteki', 'Nhlangano'], mobileMoney: ['MTN Mobile Money'], languages: ['en'] , continent: 'Africa' },
  { code: 'BW', name: 'Botswana', currency: 'BWP', dialCode: '+267', regions: ['Gaborone', 'Central', 'Kgalagadi', 'North-West'], cities: ['Gaborone', 'Francistown', 'Molepolole', 'Maun'], mobileMoney: ['Orange Money', 'Mascom MyZaka'], languages: ['en'] , continent: 'Africa' },
  { code: 'NA', name: 'Namibie', currency: 'NAD', dialCode: '+264', regions: ['Khomas', 'Erongo', 'Oshana', 'Otjozondjupa'], cities: ['Windhoek', 'Swakopmund', 'Walvis Bay', 'Oshakati', 'Rundu'], mobileMoney: ['MTC Mobile Money', 'FNB eWallet'], languages: ['en'] , continent: 'Africa' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', dialCode: '+261', regions: ['Analamanga', 'Atsinanana', 'Diana', 'Sava'], cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa'], mobileMoney: ['MVola', 'Airtel Money', 'Orange Money'], languages: ['fr', 'mg'] , continent: 'Africa' },
  { code: 'SH', name: 'Sainte-Hélène', currency: 'SHP', dialCode: '+290', regions: ['Saint Helena'], cities: ['Jamestown'], mobileMoney: [], languages: ['en'] , continent: 'Africa' },
  { code: 'RE', name: 'La Réunion', currency: 'EUR', dialCode: '+262', regions: ['Saint-Denis', 'Saint-Pierre', 'Saint-Paul'], cities: ['Saint-Denis', 'Saint-Pierre', 'Saint-Paul', 'Le Tampon'], mobileMoney: [], languages: ['fr'] , continent: 'Africa' },
  // International expansion markets
  { code: 'AE', name: 'Émirats arabes unis', currency: 'AED', dialCode: '+971', regions: ['Dubaï', 'Abu Dhabi', 'Sharjah', 'Ajman'], cities: ['Dubaï', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Al Ain'], mobileMoney: [], languages: ['ar', 'en'] , continent: 'Middle East' },
  { code: 'US', name: 'États-Unis', currency: 'USD', dialCode: '+1', regions: ['California', 'New York', 'Texas', 'Florida'], cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Miami'], mobileMoney: [], languages: ['en'] , continent: 'North America' },
  { code: 'FR', name: 'France', currency: 'EUR', dialCode: '+33', regions: ['Île-de-France', 'Auvergne-Rhône-Alpes', "Provence-Alpes-Côte d'Azur", 'Occitanie'], cities: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Bordeaux', 'Lille'], mobileMoney: [], languages: ['fr'] , continent: 'Europe' },
  { code: 'GB', name: 'Royaume-Uni', currency: 'GBP', dialCode: '+44', regions: ['England', 'Scotland', 'Wales', 'Northern Ireland'], cities: ['Londres', 'Manchester', 'Birmingham', 'Édimbourg', 'Glasgow'], mobileMoney: [], languages: ['en'] , continent: 'Europe' },
  // Reste du monde (couverture mondiale)
  // Afrique
  { code: 'GQ', name: 'Guinée équatoriale', currency: 'XAF', dialCode: '+240', regions: [], cities: ['Malabo'], mobileMoney: [], languages: ['fr', 'pt', 'es'], continent: 'Africa' },
  { code: 'YT', name: 'Mayotte', currency: 'EUR', dialCode: '+262', regions: [], cities: ['Mamoudzou'], mobileMoney: [], languages: ['fr'], continent: 'Africa' },
  { code: 'EH', name: 'Sahara Occidental', currency: 'DZD', dialCode: '+212', regions: [], cities: ['El Aaiún'], mobileMoney: [], languages: ['es'], continent: 'Africa' },
  { code: 'IO', name: 'Territoire britannique de l\'océan Indien', currency: 'USD', dialCode: '+246', regions: [], cities: ['Diego Garcia'], mobileMoney: [], languages: ['en'], continent: 'Africa' },
  // Asie
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', dialCode: '+93', regions: [], cities: ['Kabul'], mobileMoney: [], languages: ['ps', 'tk'], continent: 'Asia' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', dialCode: '+880', regions: [], cities: ['Dhaka'], mobileMoney: [], languages: ['bn'], continent: 'Asia' },
  { code: 'BT', name: 'Bhoutan', currency: 'BTN', dialCode: '+975', regions: [], cities: ['Thimphu'], mobileMoney: [], languages: ['dz'], continent: 'Asia' },
  { code: 'MM', name: 'Birmanie', currency: 'MMK', dialCode: '+95', regions: [], cities: ['Naypyidaw'], mobileMoney: [], languages: ['my'], continent: 'Asia' },
  { code: 'BN', name: 'Brunei', currency: 'BND', dialCode: '+673', regions: [], cities: ['Bandar Seri Begawan'], mobileMoney: [], languages: ['ms'], continent: 'Asia' },
  { code: 'KH', name: 'Cambodge', currency: 'KHR', dialCode: '+855', regions: [], cities: ['Phnom Penh'], mobileMoney: [], languages: ['km'], continent: 'Asia' },
  { code: 'CN', name: 'Chine', currency: 'CNY', dialCode: '+86', regions: [], cities: ['Beijing'], mobileMoney: [], languages: ['zh'], continent: 'Asia' },
  { code: 'KP', name: 'Corée du Nord', currency: 'KPW', dialCode: '+850', regions: [], cities: ['Pyongyang'], mobileMoney: [], languages: ['ko'], continent: 'Asia' },
  { code: 'KR', name: 'Corée du Sud', currency: 'KRW', dialCode: '+82', regions: [], cities: ['Seoul'], mobileMoney: [], languages: ['ko'], continent: 'Asia' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', dialCode: '+852', regions: [], cities: ['City of Victoria'], mobileMoney: [], languages: ['en', 'zh'], continent: 'Asia' },
  { code: 'IN', name: 'Inde', currency: 'INR', dialCode: '+91', regions: [], cities: ['New Delhi'], mobileMoney: [], languages: ['en', 'hi', 'ta'], continent: 'Asia' },
  { code: 'ID', name: 'Indonésie', currency: 'IDR', dialCode: '+62', regions: [], cities: ['Jakarta'], mobileMoney: [], languages: ['id'], continent: 'Asia' },
  { code: 'IR', name: 'Iran', currency: 'IRR', dialCode: '+98', regions: [], cities: ['Tehran'], mobileMoney: [], languages: ['fa'], continent: 'Asia' },
  { code: 'JP', name: 'Japon', currency: 'JPY', dialCode: '+81', regions: [], cities: ['Tokyo'], mobileMoney: [], languages: ['ja'], continent: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', dialCode: '+7', regions: [], cities: ['Astana'], mobileMoney: [], languages: ['kk', 'ru'], continent: 'Asia' },
  { code: 'KG', name: 'Kirghizistan', currency: 'KGS', dialCode: '+996', regions: [], cities: ['Bishkek'], mobileMoney: [], languages: ['ky', 'ru'], continent: 'Asia' },
  { code: 'LA', name: 'Laos', currency: 'LAK', dialCode: '+856', regions: [], cities: ['Vientiane'], mobileMoney: [], languages: ['lo'], continent: 'Asia' },
  { code: 'MO', name: 'Macao', currency: 'MOP', dialCode: '+853', regions: [], cities: [], mobileMoney: [], languages: ['pt', 'zh'], continent: 'Asia' },
  { code: 'MY', name: 'Malaisie', currency: 'MYR', dialCode: '+60', regions: [], cities: ['Kuala Lumpur'], mobileMoney: [], languages: ['en', 'ms'], continent: 'Asia' },
  { code: 'MV', name: 'Maldives', currency: 'MVR', dialCode: '+960', regions: [], cities: ['Malé'], mobileMoney: [], languages: ['dv'], continent: 'Asia' },
  { code: 'MN', name: 'Mongolie', currency: 'MNT', dialCode: '+976', regions: [], cities: ['Ulan Bator'], mobileMoney: [], languages: ['mn'], continent: 'Asia' },
  { code: 'NP', name: 'Népal', currency: 'NPR', dialCode: '+977', regions: [], cities: ['Kathmandu'], mobileMoney: [], languages: ['ne'], continent: 'Asia' },
  { code: 'UZ', name: 'Ouzbékistan', currency: 'UZS', dialCode: '+998', regions: [], cities: ['Tashkent'], mobileMoney: [], languages: ['ru', 'uz'], continent: 'Asia' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', dialCode: '+92', regions: [], cities: ['Islamabad'], mobileMoney: [], languages: ['en', 'ur'], continent: 'Asia' },
  { code: 'PH', name: 'Philippines', currency: 'PHP', dialCode: '+63', regions: [], cities: ['Manila'], mobileMoney: [], languages: ['en'], continent: 'Asia' },
  { code: 'SG', name: 'Singapour', currency: 'SGD', dialCode: '+65', regions: [], cities: ['Singapore'], mobileMoney: [], languages: ['en', 'ms', 'ta', 'zh'], continent: 'Asia' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', dialCode: '+94', regions: [], cities: ['Colombo'], mobileMoney: [], languages: ['si', 'ta'], continent: 'Asia' },
  { code: 'TJ', name: 'Tadjikistan', currency: 'TJS', dialCode: '+992', regions: [], cities: ['Dushanbe'], mobileMoney: [], languages: ['ru', 'tg'], continent: 'Asia' },
  { code: 'TW', name: 'Taïwan', currency: 'TWD', dialCode: '+886', regions: [], cities: ['Taipei'], mobileMoney: [], languages: ['zh'], continent: 'Asia' },
  { code: 'TH', name: 'Thaïlande', currency: 'THB', dialCode: '+66', regions: [], cities: ['Bangkok'], mobileMoney: [], languages: ['th'], continent: 'Asia' },
  { code: 'TL', name: 'Timor oriental', currency: 'USD', dialCode: '+670', regions: [], cities: ['Dili'], mobileMoney: [], languages: ['pt'], continent: 'Asia' },
  { code: 'TM', name: 'Turkménistan', currency: 'TMT', dialCode: '+993', regions: [], cities: ['Ashgabat'], mobileMoney: [], languages: ['ru', 'tk'], continent: 'Asia' },
  { code: 'VN', name: 'Viêt Nam', currency: 'VND', dialCode: '+84', regions: [], cities: ['Hanoi'], mobileMoney: [], languages: ['vi'], continent: 'Asia' },
  // Amérique centrale & Caraïbes
  { code: 'AI', name: 'Anguilla', currency: 'XCD', dialCode: '+1264', regions: [], cities: ['The Valley'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'AG', name: 'Antigua-et-Barbuda', currency: 'XCD', dialCode: '+1268', regions: [], cities: ['Saint John\'s'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'AW', name: 'Aruba', currency: 'AWG', dialCode: '+297', regions: [], cities: ['Oranjestad'], mobileMoney: [], languages: ['nl'], continent: 'Central America & Caribbean' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', dialCode: '+1242', regions: [], cities: ['Nassau'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'BB', name: 'Barbade', currency: 'BBD', dialCode: '+1246', regions: [], cities: ['Bridgetown'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'BZ', name: 'Belize', currency: 'BZD', dialCode: '+501', regions: [], cities: ['Belmopan'], mobileMoney: [], languages: ['en', 'es'], continent: 'Central America & Caribbean' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', dialCode: '+506', regions: [], cities: ['San José'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'CU', name: 'Cuba', currency: 'CUC', dialCode: '+53', regions: [], cities: ['Havana'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'CW', name: 'Curaçao', currency: 'ANG', dialCode: '+599', regions: [], cities: ['Willemstad'], mobileMoney: [], languages: ['en', 'nl'], continent: 'Central America & Caribbean' },
  { code: 'DM', name: 'Dominique', currency: 'XCD', dialCode: '+1767', regions: [], cities: ['Roseau'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'GD', name: 'Grenade', currency: 'XCD', dialCode: '+1473', regions: [], cities: ['St. George\'s'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'GP', name: 'Guadeloupe', currency: 'EUR', dialCode: '+590', regions: [], cities: ['Basse-Terre'], mobileMoney: [], languages: ['fr'], continent: 'Central America & Caribbean' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', dialCode: '+502', regions: [], cities: ['Guatemala City'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'HT', name: 'Haïti', currency: 'HTG', dialCode: '+509', regions: [], cities: ['Port-au-Prince'], mobileMoney: [], languages: ['fr', 'ht'], continent: 'Central America & Caribbean' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', dialCode: '+504', regions: [], cities: ['Tegucigalpa'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'KY', name: 'Îles Caïmans', currency: 'KYD', dialCode: '+1345', regions: [], cities: ['George Town'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'TC', name: 'Îles Turques-et-Caïques', currency: 'USD', dialCode: '+1649', regions: [], cities: ['Cockburn Town'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'VG', name: 'Îles Vierges britanniques', currency: 'USD', dialCode: '+1284', regions: [], cities: ['Road Town'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'VI', name: 'Îles Vierges des États-Unis', currency: 'USD', dialCode: '+1340', regions: [], cities: ['Charlotte Amalie'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'JM', name: 'Jamaïque', currency: 'JMD', dialCode: '+1876', regions: [], cities: ['Kingston'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'MQ', name: 'Martinique', currency: 'EUR', dialCode: '+596', regions: [], cities: ['Fort-de-France'], mobileMoney: [], languages: ['fr'], continent: 'Central America & Caribbean' },
  { code: 'MS', name: 'Montserrat', currency: 'XCD', dialCode: '+1664', regions: [], cities: ['Plymouth'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', dialCode: '+505', regions: [], cities: ['Managua'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'PA', name: 'Panama', currency: 'PAB', dialCode: '+507', regions: [], cities: ['Panama City'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'BQ', name: 'Pays-Bas caribéens', currency: 'USD', dialCode: '+599', regions: [], cities: ['Kralendijk'], mobileMoney: [], languages: ['en', 'nl'], continent: 'Central America & Caribbean' },
  { code: 'PR', name: 'Porto Rico', currency: 'USD', dialCode: '+1', regions: [], cities: ['San Juan'], mobileMoney: [], languages: ['en', 'es'], continent: 'Central America & Caribbean' },
  { code: 'DO', name: 'République dominicaine', currency: 'DOP', dialCode: '+1', regions: [], cities: ['Santo Domingo'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'BL', name: 'Saint-Barthélemy', currency: 'EUR', dialCode: '+590', regions: [], cities: ['Gustavia'], mobileMoney: [], languages: ['fr'], continent: 'Central America & Caribbean' },
  { code: 'KN', name: 'Saint-Christophe-et-Niévès', currency: 'XCD', dialCode: '+1869', regions: [], cities: ['Basseterre'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'MF', name: 'Saint-Martin', currency: 'EUR', dialCode: '+590', regions: [], cities: ['Marigot'], mobileMoney: [], languages: ['fr'], continent: 'Central America & Caribbean' },
  { code: 'SX', name: 'Saint-Martin', currency: 'ANG', dialCode: '+1721', regions: [], cities: ['Philipsburg'], mobileMoney: [], languages: ['en', 'fr', 'nl'], continent: 'Central America & Caribbean' },
  { code: 'VC', name: 'Saint-Vincent-et-les-Grenadines', currency: 'XCD', dialCode: '+1784', regions: [], cities: ['Kingstown'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'LC', name: 'Sainte-Lucie', currency: 'XCD', dialCode: '+1758', regions: [], cities: ['Castries'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  { code: 'SV', name: 'Salvador', currency: 'USD', dialCode: '+503', regions: [], cities: ['San Salvador'], mobileMoney: [], languages: ['es'], continent: 'Central America & Caribbean' },
  { code: 'TT', name: 'Trinité-et-Tobago', currency: 'TTD', dialCode: '+1868', regions: [], cities: ['Port of Spain'], mobileMoney: [], languages: ['en'], continent: 'Central America & Caribbean' },
  // Europe
  { code: 'AX', name: 'Ahvenanmaa', currency: 'EUR', dialCode: '+35818', regions: [], cities: ['Mariehamn'], mobileMoney: [], languages: ['sv'], continent: 'Europe' },
  { code: 'AL', name: 'Albanie', currency: 'ALL', dialCode: '+355', regions: [], cities: ['Tirana'], mobileMoney: [], languages: ['sq'], continent: 'Europe' },
  { code: 'DE', name: 'Allemagne', currency: 'EUR', dialCode: '+49', regions: [], cities: ['Berlin'], mobileMoney: [], languages: ['de'], continent: 'Europe' },
  { code: 'AD', name: 'Andorre', currency: 'EUR', dialCode: '+376', regions: [], cities: ['Andorra la Vella'], mobileMoney: [], languages: ['ca'], continent: 'Europe' },
  { code: 'AT', name: 'Autriche', currency: 'EUR', dialCode: '+43', regions: [], cities: ['Vienna'], mobileMoney: [], languages: ['en'], continent: 'Europe' },
  { code: 'BE', name: 'Belgique', currency: 'EUR', dialCode: '+32', regions: [], cities: ['Brussels'], mobileMoney: [], languages: ['de', 'fr', 'nl'], continent: 'Europe' },
  { code: 'BY', name: 'Biélorussie', currency: 'BYN', dialCode: '+375', regions: [], cities: ['Minsk'], mobileMoney: [], languages: ['be', 'ru'], continent: 'Europe' },
  { code: 'BA', name: 'Bosnie-Herzégovine', currency: 'BAM', dialCode: '+387', regions: [], cities: ['Sarajevo'], mobileMoney: [], languages: ['bs', 'hr', 'sr'], continent: 'Europe' },
  { code: 'BG', name: 'Bulgarie', currency: 'BGN', dialCode: '+359', regions: [], cities: ['Sofia'], mobileMoney: [], languages: ['bg'], continent: 'Europe' },
  { code: 'CY', name: 'Chypre', currency: 'EUR', dialCode: '+357', regions: [], cities: ['Nicosia'], mobileMoney: [], languages: ['el', 'tr'], continent: 'Europe' },
  { code: 'VA', name: 'Cité du Vatican', currency: 'EUR', dialCode: '+39', regions: [], cities: ['Vatican City'], mobileMoney: [], languages: ['it', 'la'], continent: 'Europe' },
  { code: 'HR', name: 'Croatie', currency: 'EUR', dialCode: '+385', regions: [], cities: ['Zagreb'], mobileMoney: [], languages: ['hr'], continent: 'Europe' },
  { code: 'DK', name: 'Danemark', currency: 'DKK', dialCode: '+45', regions: [], cities: ['Copenhagen'], mobileMoney: [], languages: ['da'], continent: 'Europe' },
  { code: 'ES', name: 'Espagne', currency: 'EUR', dialCode: '+34', regions: [], cities: ['Madrid'], mobileMoney: [], languages: ['es'], continent: 'Europe' },
  { code: 'EE', name: 'Estonie', currency: 'EUR', dialCode: '+372', regions: [], cities: ['Tallinn'], mobileMoney: [], languages: ['et'], continent: 'Europe' },
  { code: 'FI', name: 'Finlande', currency: 'EUR', dialCode: '+358', regions: [], cities: ['Helsinki'], mobileMoney: [], languages: ['fi', 'sv'], continent: 'Europe' },
  { code: 'GI', name: 'Gibraltar', currency: 'GIP', dialCode: '+350', regions: [], cities: ['Gibraltar'], mobileMoney: [], languages: ['en'], continent: 'Europe' },
  { code: 'GR', name: 'Grèce', currency: 'EUR', dialCode: '+30', regions: [], cities: ['Athens'], mobileMoney: [], languages: ['el'], continent: 'Europe' },
  { code: 'GG', name: 'Guernesey', currency: 'GBP', dialCode: '+44', regions: [], cities: ['St. Peter Port'], mobileMoney: [], languages: ['en', 'fr'], continent: 'Europe' },
  { code: 'HU', name: 'Hongrie', currency: 'HUF', dialCode: '+36', regions: [], cities: ['Budapest'], mobileMoney: [], languages: ['hu'], continent: 'Europe' },
  { code: 'IM', name: 'Île de Man', currency: 'GBP', dialCode: '+44', regions: [], cities: ['Douglas'], mobileMoney: [], languages: ['en', 'gv'], continent: 'Europe' },
  { code: 'FO', name: 'Îles Féroé', currency: 'DKK', dialCode: '+298', regions: [], cities: ['Tórshavn'], mobileMoney: [], languages: ['da', 'fo'], continent: 'Europe' },
  { code: 'IE', name: 'Irlande', currency: 'EUR', dialCode: '+353', regions: [], cities: ['Dublin'], mobileMoney: [], languages: ['en', 'ga'], continent: 'Europe' },
  { code: 'IS', name: 'Islande', currency: 'ISK', dialCode: '+354', regions: [], cities: ['Reykjavik'], mobileMoney: [], languages: ['is'], continent: 'Europe' },
  { code: 'IT', name: 'Italie', currency: 'EUR', dialCode: '+39', regions: [], cities: ['Rome'], mobileMoney: [], languages: ['it'], continent: 'Europe' },
  { code: 'JE', name: 'Jersey', currency: 'GBP', dialCode: '+44', regions: [], cities: ['Saint Helier'], mobileMoney: [], languages: ['en', 'fr'], continent: 'Europe' },
  { code: 'XK', name: 'Kosovo', currency: 'EUR', dialCode: '+383', regions: [], cities: ['Pristina'], mobileMoney: [], languages: ['sq', 'sr'], continent: 'Europe' },
  { code: 'LV', name: 'Lettonie', currency: 'EUR', dialCode: '+371', regions: [], cities: ['Riga'], mobileMoney: [], languages: ['lv'], continent: 'Europe' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', dialCode: '+423', regions: [], cities: ['Vaduz'], mobileMoney: [], languages: ['de'], continent: 'Europe' },
  { code: 'LT', name: 'Lituanie', currency: 'EUR', dialCode: '+370', regions: [], cities: ['Vilnius'], mobileMoney: [], languages: ['lt'], continent: 'Europe' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', dialCode: '+352', regions: [], cities: ['Luxembourg'], mobileMoney: [], languages: ['de', 'fr', 'lb'], continent: 'Europe' },
  { code: 'MK', name: 'Macédoine du Nord', currency: 'MKD', dialCode: '+389', regions: [], cities: ['Skopje'], mobileMoney: [], languages: ['mk'], continent: 'Europe' },
  { code: 'MT', name: 'Malte', currency: 'EUR', dialCode: '+356', regions: [], cities: ['Valletta'], mobileMoney: [], languages: ['en', 'mt'], continent: 'Europe' },
  { code: 'MD', name: 'Moldavie', currency: 'MDL', dialCode: '+373', regions: [], cities: ['Chișinău'], mobileMoney: [], languages: ['ro'], continent: 'Europe' },
  { code: 'MC', name: 'Monaco', currency: 'EUR', dialCode: '+377', regions: [], cities: ['Monaco'], mobileMoney: [], languages: ['fr'], continent: 'Europe' },
  { code: 'ME', name: 'Monténégro', currency: 'EUR', dialCode: '+382', regions: [], cities: ['Podgorica'], mobileMoney: [], languages: ['en'], continent: 'Europe' },
  { code: 'NO', name: 'Norvège', currency: 'NOK', dialCode: '+47', regions: [], cities: ['Oslo'], mobileMoney: [], languages: ['nn', 'nb'], continent: 'Europe' },
  { code: 'NL', name: 'Pays-Bas', currency: 'EUR', dialCode: '+31', regions: [], cities: ['Amsterdam'], mobileMoney: [], languages: ['nl'], continent: 'Europe' },
  { code: 'PL', name: 'Pologne', currency: 'PLN', dialCode: '+48', regions: [], cities: ['Warsaw'], mobileMoney: [], languages: ['pl'], continent: 'Europe' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', dialCode: '+351', regions: [], cities: ['Lisbon'], mobileMoney: [], languages: ['pt'], continent: 'Europe' },
  { code: 'RO', name: 'Roumanie', currency: 'RON', dialCode: '+40', regions: [], cities: ['Bucharest'], mobileMoney: [], languages: ['ro'], continent: 'Europe' },
  { code: 'RU', name: 'Russie', currency: 'RUB', dialCode: '+7', regions: [], cities: ['Moscow'], mobileMoney: [], languages: ['ru'], continent: 'Europe' },
  { code: 'SM', name: 'Saint-Marin', currency: 'EUR', dialCode: '+378', regions: [], cities: ['City of San Marino'], mobileMoney: [], languages: ['it'], continent: 'Europe' },
  { code: 'RS', name: 'Serbie', currency: 'RSD', dialCode: '+381', regions: [], cities: ['Belgrade'], mobileMoney: [], languages: ['sr'], continent: 'Europe' },
  { code: 'SK', name: 'Slovaquie', currency: 'EUR', dialCode: '+421', regions: [], cities: ['Bratislava'], mobileMoney: [], languages: ['sk'], continent: 'Europe' },
  { code: 'SI', name: 'Slovénie', currency: 'EUR', dialCode: '+386', regions: [], cities: ['Ljubljana'], mobileMoney: [], languages: ['sl'], continent: 'Europe' },
  { code: 'SE', name: 'Suède', currency: 'SEK', dialCode: '+46', regions: [], cities: ['Stockholm'], mobileMoney: [], languages: ['sv'], continent: 'Europe' },
  { code: 'CH', name: 'Suisse', currency: 'CHF', dialCode: '+41', regions: [], cities: ['Bern'], mobileMoney: [], languages: ['fr', 'it', 'rm'], continent: 'Europe' },
  { code: 'SJ', name: 'Svalbard et Jan Mayen', currency: 'NOK', dialCode: '+4779', regions: [], cities: ['Longyearbyen'], mobileMoney: [], languages: ['no'], continent: 'Europe' },
  { code: 'CZ', name: 'Tchéquie', currency: 'CZK', dialCode: '+420', regions: [], cities: ['Prague'], mobileMoney: [], languages: ['cs', 'sk'], continent: 'Europe' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', dialCode: '+380', regions: [], cities: ['Kyiv'], mobileMoney: [], languages: ['uk'], continent: 'Europe' },
  // Moyen-Orient
  { code: 'SA', name: 'Arabie Saoudite', currency: 'SAR', dialCode: '+966', regions: [], cities: ['Riyadh'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'AM', name: 'Arménie', currency: 'AMD', dialCode: '+374', regions: [], cities: ['Yerevan'], mobileMoney: [], languages: ['hy'], continent: 'Middle East' },
  { code: 'AZ', name: 'Azerbaïdjan', currency: 'AZN', dialCode: '+994', regions: [], cities: ['Baku'], mobileMoney: [], languages: ['az', 'ru'], continent: 'Middle East' },
  { code: 'BH', name: 'Bahreïn', currency: 'BHD', dialCode: '+973', regions: [], cities: ['Manama'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'GE', name: 'Géorgie', currency: 'GEL', dialCode: '+995', regions: [], cities: ['Tbilisi'], mobileMoney: [], languages: ['ka'], continent: 'Middle East' },
  { code: 'IQ', name: 'Irak', currency: 'IQD', dialCode: '+964', regions: [], cities: ['Baghdad'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'IL', name: 'Israël', currency: 'ILS', dialCode: '+972', regions: [], cities: ['Jerusalem'], mobileMoney: [], languages: ['ar', 'he'], continent: 'Middle East' },
  { code: 'JO', name: 'Jordanie', currency: 'JOD', dialCode: '+962', regions: [], cities: ['Amman'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'KW', name: 'Koweït', currency: 'KWD', dialCode: '+965', regions: [], cities: ['Kuwait City'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'LB', name: 'Liban', currency: 'LBP', dialCode: '+961', regions: [], cities: ['Beirut'], mobileMoney: [], languages: ['ar', 'fr'], continent: 'Middle East' },
  { code: 'OM', name: 'Oman', currency: 'OMR', dialCode: '+968', regions: [], cities: ['Muscat'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'PS', name: 'Palestine', currency: 'EGP', dialCode: '+970', regions: [], cities: ['Ramallah'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'QA', name: 'Qatar', currency: 'QAR', dialCode: '+974', regions: [], cities: ['Doha'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'SY', name: 'Syrie', currency: 'SYP', dialCode: '+963', regions: [], cities: ['Damascus'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  { code: 'TR', name: 'Turquie', currency: 'TRY', dialCode: '+90', regions: [], cities: ['Ankara'], mobileMoney: [], languages: ['tr'], continent: 'Middle East' },
  { code: 'YE', name: 'Yémen', currency: 'YER', dialCode: '+967', regions: [], cities: ['Sana\'a'], mobileMoney: [], languages: ['ar'], continent: 'Middle East' },
  // Amérique du Nord
  { code: 'BM', name: 'Bermudes', currency: 'BMD', dialCode: '+1441', regions: [], cities: ['Hamilton'], mobileMoney: [], languages: ['en'], continent: 'North America' },
  { code: 'CA', name: 'Canada', currency: 'CAD', dialCode: '+1', regions: [], cities: ['Ottawa'], mobileMoney: [], languages: ['en', 'fr'], continent: 'North America' },
  { code: 'GL', name: 'Groenland', currency: 'DKK', dialCode: '+299', regions: [], cities: ['Nuuk'], mobileMoney: [], languages: ['kl'], continent: 'North America' },
  { code: 'MX', name: 'Mexique', currency: 'MXN', dialCode: '+52', regions: [], cities: ['Mexico City'], mobileMoney: [], languages: ['es'], continent: 'North America' },
  { code: 'PM', name: 'Saint-Pierre-et-Miquelon', currency: 'EUR', dialCode: '+508', regions: [], cities: ['Saint-Pierre'], mobileMoney: [], languages: ['fr'], continent: 'North America' },
  // Océanie
  { code: 'AU', name: 'Australie', currency: 'AUD', dialCode: '+61', regions: [], cities: ['Canberra'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'FJ', name: 'Fidji', currency: 'FJD', dialCode: '+679', regions: [], cities: ['Suva'], mobileMoney: [], languages: ['en', 'fj'], continent: 'Oceania' },
  { code: 'GU', name: 'Guam', currency: 'USD', dialCode: '+1671', regions: [], cities: ['Hagåtña'], mobileMoney: [], languages: ['ch', 'en', 'es'], continent: 'Oceania' },
  { code: 'CX', name: 'Île Christmas', currency: 'AUD', dialCode: '+61', regions: [], cities: ['Flying Fish Cove'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'NF', name: 'Île Norfolk', currency: 'AUD', dialCode: '+672', regions: [], cities: ['Kingston'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'CC', name: 'Îles Cocos', currency: 'AUD', dialCode: '+61', regions: [], cities: ['West Island'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'CK', name: 'Îles Cook', currency: 'CKD', dialCode: '+682', regions: [], cities: ['Avarua'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'MP', name: 'Îles Mariannes du Nord', currency: 'USD', dialCode: '+1670', regions: [], cities: ['Saipan'], mobileMoney: [], languages: ['ch', 'en'], continent: 'Oceania' },
  { code: 'MH', name: 'Îles Marshall', currency: 'USD', dialCode: '+692', regions: [], cities: ['Majuro'], mobileMoney: [], languages: ['en', 'mh'], continent: 'Oceania' },
  { code: 'PN', name: 'Îles Pitcairn', currency: 'NZD', dialCode: '+64', regions: [], cities: ['Adamstown'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'SB', name: 'Îles Salomon', currency: 'SBD', dialCode: '+677', regions: [], cities: ['Honiara'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', dialCode: '+686', regions: [], cities: ['South Tarawa'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'FM', name: 'Micronésie', currency: 'USD', dialCode: '+691', regions: [], cities: ['Palikir'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'NR', name: 'Nauru', currency: 'AUD', dialCode: '+674', regions: [], cities: ['Yaren'], mobileMoney: [], languages: ['en', 'na'], continent: 'Oceania' },
  { code: 'NU', name: 'Niue', currency: 'NZD', dialCode: '+683', regions: [], cities: ['Alofi'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'NC', name: 'Nouvelle-Calédonie', currency: 'XPF', dialCode: '+687', regions: [], cities: ['Nouméa'], mobileMoney: [], languages: ['fr'], continent: 'Oceania' },
  { code: 'NZ', name: 'Nouvelle-Zélande', currency: 'NZD', dialCode: '+64', regions: [], cities: ['Wellington'], mobileMoney: [], languages: ['en', 'mi'], continent: 'Oceania' },
  { code: 'PW', name: 'Palaos (Palau)', currency: 'USD', dialCode: '+680', regions: [], cities: ['Ngerulmud'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', currency: 'PGK', dialCode: '+675', regions: [], cities: ['Port Moresby'], mobileMoney: [], languages: ['en', 'ho'], continent: 'Oceania' },
  { code: 'PF', name: 'Polynésie française', currency: 'XPF', dialCode: '+689', regions: [], cities: ['Papeetē'], mobileMoney: [], languages: ['fr'], continent: 'Oceania' },
  { code: 'WS', name: 'Samoa', currency: 'WST', dialCode: '+685', regions: [], cities: ['Apia'], mobileMoney: [], languages: ['en', 'sm'], continent: 'Oceania' },
  { code: 'AS', name: 'Samoa américaines', currency: 'USD', dialCode: '+1684', regions: [], cities: ['Pago Pago'], mobileMoney: [], languages: ['en', 'sm'], continent: 'Oceania' },
  { code: 'TK', name: 'Tokelau', currency: 'NZD', dialCode: '+690', regions: [], cities: ['Fakaofo'], mobileMoney: [], languages: ['en', 'sm'], continent: 'Oceania' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', dialCode: '+676', regions: [], cities: ['Nuku\'alofa'], mobileMoney: [], languages: ['en', 'to'], continent: 'Oceania' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', dialCode: '+688', regions: [], cities: ['Funafuti'], mobileMoney: [], languages: ['en'], continent: 'Oceania' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', dialCode: '+678', regions: [], cities: ['Port Vila'], mobileMoney: [], languages: ['bi', 'en', 'fr'], continent: 'Oceania' },
  { code: 'WF', name: 'Wallis-et-Futuna', currency: 'XPF', dialCode: '+681', regions: [], cities: ['Mata-Utu'], mobileMoney: [], languages: ['fr'], continent: 'Oceania' },
  // Amérique du Sud
  { code: 'AR', name: 'Argentine', currency: 'ARS', dialCode: '+54', regions: [], cities: ['Buenos Aires'], mobileMoney: [], languages: ['gn', 'es'], continent: 'South America' },
  { code: 'BO', name: 'Bolivie', currency: 'BOB', dialCode: '+591', regions: [], cities: ['Sucre'], mobileMoney: [], languages: ['ay', 'gn', 'qu', 'es'], continent: 'South America' },
  { code: 'BR', name: 'Brésil', currency: 'BRL', dialCode: '+55', regions: [], cities: ['Brasília'], mobileMoney: [], languages: ['pt'], continent: 'South America' },
  { code: 'CL', name: 'Chili', currency: 'CLP', dialCode: '+56', regions: [], cities: ['Santiago'], mobileMoney: [], languages: ['es'], continent: 'South America' },
  { code: 'CO', name: 'Colombie', currency: 'COP', dialCode: '+57', regions: [], cities: ['Bogotá'], mobileMoney: [], languages: ['es'], continent: 'South America' },
  { code: 'EC', name: 'Équateur', currency: 'USD', dialCode: '+593', regions: [], cities: ['Quito'], mobileMoney: [], languages: ['es'], continent: 'South America' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', dialCode: '+592', regions: [], cities: ['Georgetown'], mobileMoney: [], languages: ['en'], continent: 'South America' },
  { code: 'GF', name: 'Guyane', currency: 'EUR', dialCode: '+594', regions: [], cities: ['Cayenne'], mobileMoney: [], languages: ['fr'], continent: 'South America' },
  { code: 'FK', name: 'Îles Malouines', currency: 'FKP', dialCode: '+500', regions: [], cities: ['Stanley'], mobileMoney: [], languages: ['en'], continent: 'South America' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', dialCode: '+595', regions: [], cities: ['Asunción'], mobileMoney: [], languages: ['gn', 'es'], continent: 'South America' },
  { code: 'PE', name: 'Pérou', currency: 'PEN', dialCode: '+51', regions: [], cities: ['Lima'], mobileMoney: [], languages: ['ay', 'qu', 'es'], continent: 'South America' },
  { code: 'SR', name: 'Surinam', currency: 'SRD', dialCode: '+597', regions: [], cities: ['Paramaribo'], mobileMoney: [], languages: ['nl'], continent: 'South America' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', dialCode: '+598', regions: [], cities: ['Montevideo'], mobileMoney: [], languages: ['es'], continent: 'South America' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', dialCode: '+58', regions: [], cities: ['Caracas'], mobileMoney: [], languages: ['es'], continent: 'South America' },
];

export const CURRENCIES: Record<string, { symbol: string; decimals: number; label: string }> = {
  XAF: { symbol: 'FCFA', decimals: 0, label: 'Franc CFA (BEAC)' },
  XOF: { symbol: 'FCFA', decimals: 0, label: 'Franc CFA (BCEAO)' },
  NGN: { symbol: '₦', decimals: 2, label: 'Naira' },
  GHS: { symbol: '₵', decimals: 2, label: 'Cedi' },
  KES: { symbol: 'KSh', decimals: 2, label: 'Shilling kényan' },
  ZAR: { symbol: 'R', decimals: 2, label: 'Rand' },
  EGP: { symbol: 'E£', decimals: 2, label: 'Livre égyptienne' },
  MAD: { symbol: 'DH', decimals: 2, label: 'Dirham' },
  DZD: { symbol: 'DA', decimals: 2, label: 'Dinar algérien' },
  ETB: { symbol: 'Br', decimals: 2, label: 'Birr' },
  TZS: { symbol: 'TSh', decimals: 0, label: 'Shilling tanzanien' },
  UGX: { symbol: 'USh', decimals: 0, label: 'Shilling ougandais' },
  USD: { symbol: '$', decimals: 2, label: 'Dollar américain' },
  EUR: { symbol: '€', decimals: 2, label: 'Euro' },
  GBP: { symbol: '£', decimals: 2, label: 'Livre sterling' },
  AED: { symbol: 'AED', decimals: 2, label: 'Dirham des EAU' },
  CDF: { symbol: 'FC', decimals: 2, label: 'Franc congolais' },
  GNF: { symbol: 'GNF', decimals: 0, label: 'Franc guinéen' },
  SLL: { symbol: 'Le', decimals: 2, label: 'Leone' },
  LRD: { symbol: 'L$', decimals: 2, label: 'Dollar libérien' },
  RWF: { symbol: 'RF', decimals: 0, label: 'Franc rwandais' },
  BIF: { symbol: 'FBu', decimals: 0, label: 'Franc burundais' },
  MWK: { symbol: 'MK', decimals: 2, label: 'Kwacha malawite' },
  ZMW: { symbol: 'ZK', decimals: 2, label: 'Kwacha zambien' },
  ZWL: { symbol: 'ZWL', decimals: 2, label: 'Dollar zimbabwéen' },
  MZN: { symbol: 'MT', decimals: 2, label: 'Metical' },
  AOA: { symbol: 'Kz', decimals: 2, label: 'Kwanza' },
  SDG: { symbol: 'SDG', decimals: 2, label: 'Livre soudanaise' },
  TND: { symbol: 'DT', decimals: 3, label: 'Dinar tunisien' },
  LYD: { symbol: 'LD', decimals: 3, label: 'Dinar libyen' },
  MRU: { symbol: 'MRU', decimals: 2, label: 'Ouguiya' },
  GMD: { symbol: 'D', decimals: 2, label: 'Dalasi' },
  CVE: { symbol: '$', decimals: 2, label: 'Escudo capverdien' },
  KMF: { symbol: 'CF', decimals: 0, label: 'Franc comorien' },
  SCR: { symbol: 'SR', decimals: 2, label: 'Roupie seychelloise' },
  MUR: { symbol: 'Rs', decimals: 2, label: 'Roupie mauricienne' },
  STN: { symbol: 'Db', decimals: 2, label: 'Dobra' },
  DJF: { symbol: 'FDJ', decimals: 0, label: 'Franc djiboutien' },
  SOS: { symbol: 'SOS', decimals: 2, label: 'Shilling somalien' },
  SSP: { symbol: 'SSP', decimals: 2, label: 'Livre soudanaise du Sud' },
  ERN: { symbol: 'Nfk', decimals: 2, label: 'Nakfa' },
  LSL: { symbol: 'L', decimals: 2, label: 'Loti' },
  SZL: { symbol: 'L', decimals: 2, label: 'Lilangeni' },
  BWP: { symbol: 'P', decimals: 2, label: 'Pula' },
  NAD: { symbol: 'N$', decimals: 2, label: 'Dollar namibien' },
  MGA: { symbol: 'Ar', decimals: 2, label: 'Ariary' },
  SHP: { symbol: '£', decimals: 2, label: 'Livre de Sainte-Hélène' },
  AFN: { symbol: '؋', decimals: 2, label: 'Afghani' },
  ALL: { symbol: 'L', decimals: 2, label: 'Lek albanais' },
  AMD: { symbol: '֏', decimals: 2, label: 'Dram arménien' },
  ANG: { symbol: 'NAf', decimals: 2, label: 'Florin antillais' },
  ARS: { symbol: 'AR$', decimals: 2, label: 'Peso argentin' },
  AUD: { symbol: '$', decimals: 2, label: 'Dollar australien' },
  AWG: { symbol: 'ƒ', decimals: 2, label: 'Florin arubais' },
  AZN: { symbol: '₼', decimals: 2, label: 'Manat azerbaïdjanais' },
  BAM: { symbol: 'KM', decimals: 2, label: 'Mark convertible' },
  BBD: { symbol: 'Bds$', decimals: 2, label: 'Dollar barbadien' },
  BDT: { symbol: '৳', decimals: 2, label: 'Taka bangladais' },
  BGN: { symbol: 'BGN', decimals: 2, label: 'Bulgarian Lev' },
  BHD: { symbol: 'BD', decimals: 3, label: 'Dinar bahreïni' },
  BMD: { symbol: 'BD$', decimals: 2, label: 'Dollar bermudien' },
  BND: { symbol: 'B$', decimals: 2, label: 'Dollar de Brunei' },
  BOB: { symbol: 'Bs', decimals: 2, label: 'Boliviano' },
  BRL: { symbol: 'R$', decimals: 2, label: 'Real brésilien' },
  BSD: { symbol: 'B$', decimals: 2, label: 'Dollar bahaméen' },
  BTN: { symbol: 'Nu.', decimals: 2, label: 'Ngultrum bhoutanais' },
  BYN: { symbol: 'Br', decimals: 2, label: 'Rouble biélorusse' },
  BZD: { symbol: 'BZ$', decimals: 2, label: 'Dollar bélizien' },
  CAD: { symbol: '$', decimals: 2, label: 'Dollar canadien' },
  CHF: { symbol: 'CHF', decimals: 2, label: 'Franc suisse' },
  CKD: { symbol: '$', decimals: 2, label: 'Dollar des îles Cook' },
  CLP: { symbol: 'CLP$', decimals: 0, label: 'Peso chilien' },
  CNY: { symbol: '¥', decimals: 2, label: 'Yuan chinois' },
  COP: { symbol: 'COL$', decimals: 2, label: 'Peso colombien' },
  CRC: { symbol: '₡', decimals: 2, label: 'Colon costaricien' },
  CUC: { symbol: 'CUC$', decimals: 2, label: 'Peso cubain convertible' },
  CZK: { symbol: 'Kč', decimals: 2, label: 'Couronne tchèque' },
  DKK: { symbol: 'kr', decimals: 2, label: 'Couronne danoise' },
  DOP: { symbol: 'RD$', decimals: 2, label: 'Peso dominicain' },
  FJD: { symbol: 'FJ$', decimals: 2, label: 'Dollar fidjien' },
  FKP: { symbol: '£', decimals: 2, label: 'Livre des Malouines' },
  GEL: { symbol: '₾', decimals: 2, label: 'Lari géorgien' },
  GIP: { symbol: '£', decimals: 2, label: 'Livre de Gibraltar' },
  GTQ: { symbol: 'Q', decimals: 2, label: 'Quetzal guatémaltèque' },
  GYD: { symbol: 'GY$', decimals: 2, label: 'Dollar guyanien' },
  HKD: { symbol: 'HK$', decimals: 2, label: 'Dollar de Hong Kong' },
  HNL: { symbol: 'L', decimals: 2, label: 'Lempira hondurien' },
  HTG: { symbol: 'G', decimals: 2, label: 'Gourde haïtienne' },
  HUF: { symbol: 'Ft', decimals: 2, label: 'Forint hongrois' },
  IDR: { symbol: 'Rp', decimals: 2, label: 'Roupie indonésienne' },
  ILS: { symbol: '₪', decimals: 2, label: 'Shekel israélien' },
  INR: { symbol: '₹', decimals: 2, label: 'Roupie indienne' },
  IQD: { symbol: 'ID', decimals: 3, label: 'Dinar irakien' },
  IRR: { symbol: 'Rl', decimals: 2, label: 'Rial iranien' },
  ISK: { symbol: 'kr', decimals: 0, label: 'Couronne islandaise' },
  JMD: { symbol: 'J$', decimals: 2, label: 'Dollar jamaïcain' },
  JOD: { symbol: 'JD', decimals: 3, label: 'Dinar jordanien' },
  JPY: { symbol: '¥', decimals: 0, label: 'Yen japonais' },
  KGS: { symbol: 'с', decimals: 2, label: 'Som kirghize' },
  KHR: { symbol: '៛', decimals: 2, label: 'Riel cambodgien' },
  KPW: { symbol: '₩', decimals: 2, label: 'Won nord-coréen' },
  KRW: { symbol: '₩', decimals: 0, label: 'Won sud-coréen' },
  KWD: { symbol: 'KD', decimals: 3, label: 'Dinar koweïtien' },
  KYD: { symbol: 'CI$', decimals: 2, label: 'Dollar caïmanais' },
  KZT: { symbol: '₸', decimals: 2, label: 'Tenge kazakh' },
  LAK: { symbol: '₭', decimals: 2, label: 'Kip laotien' },
  LBP: { symbol: 'LL', decimals: 2, label: 'Livre libanaise' },
  LKR: { symbol: 'Rs', decimals: 2, label: 'Roupie srilankaise' },
  MDL: { symbol: 'L', decimals: 2, label: 'Leu moldave' },
  MKD: { symbol: 'ден', decimals: 2, label: 'Denar macédonien' },
  MMK: { symbol: 'K', decimals: 2, label: 'Kyat birman' },
  MNT: { symbol: '₮', decimals: 2, label: 'Tugrik mongol' },
  MOP: { symbol: 'MOP$', decimals: 2, label: 'Pataca macanaise' },
  MVR: { symbol: 'Rf', decimals: 2, label: 'Rufiyaa maldivienne' },
  MXN: { symbol: '$', decimals: 2, label: 'Peso mexicain' },
  MYR: { symbol: 'RM', decimals: 2, label: 'Ringgit malaisien' },
  NIO: { symbol: 'C$', decimals: 2, label: 'Cordoba nicaraguayen' },
  NOK: { symbol: 'kr', decimals: 2, label: 'Couronne norvégienne' },
  NPR: { symbol: 'Rs', decimals: 2, label: 'Roupie népalaise' },
  NZD: { symbol: 'NZ$', decimals: 2, label: 'Dollar néo-zélandais' },
  OMR: { symbol: 'OR', decimals: 3, label: 'Rial omanais' },
  PAB: { symbol: 'B/.', decimals: 2, label: 'Balboa panaméen' },
  PEN: { symbol: 'S/', decimals: 2, label: 'Sol péruvien' },
  PGK: { symbol: 'K', decimals: 2, label: 'Kina papouan' },
  PHP: { symbol: '₱', decimals: 2, label: 'Peso philippin' },
  PKR: { symbol: 'Rs', decimals: 2, label: 'Roupie pakistanaise' },
  PLN: { symbol: 'zł', decimals: 2, label: 'Zloty polonais' },
  PYG: { symbol: '₲', decimals: 0, label: 'Guarani paraguayen' },
  QAR: { symbol: 'QR', decimals: 2, label: 'Riyal qatari' },
  RON: { symbol: 'lei', decimals: 2, label: 'Leu roumain' },
  RSD: { symbol: 'дин', decimals: 2, label: 'Dinar serbe' },
  RUB: { symbol: '₽', decimals: 2, label: 'Rouble russe' },
  SAR: { symbol: 'SR', decimals: 2, label: 'Riyal saoudien' },
  SBD: { symbol: 'SI$', decimals: 2, label: 'Dollar des Îles Salomon' },
  SEK: { symbol: 'kr', decimals: 2, label: 'Couronne suédoise' },
  SGD: { symbol: 'S$', decimals: 2, label: 'Dollar de Singapour' },
  SRD: { symbol: 'SR$', decimals: 2, label: 'Dollar surinamais' },
  SYP: { symbol: 'SP', decimals: 2, label: 'Livre syrienne' },
  THB: { symbol: '฿', decimals: 2, label: 'Baht thaïlandais' },
  TJS: { symbol: 'SM', decimals: 2, label: 'Somoni tadjik' },
  TMT: { symbol: 'm', decimals: 2, label: 'Manat turkmène' },
  TOP: { symbol: 'T$', decimals: 2, label: 'Paʻanga tongien' },
  TRY: { symbol: '₺', decimals: 2, label: 'Livre turque' },
  TTD: { symbol: 'TT$', decimals: 2, label: 'Dollar de Trinité-et-Tobago' },
  TWD: { symbol: 'NT$', decimals: 2, label: 'Dollar taïwanais' },
  UAH: { symbol: '₴', decimals: 2, label: 'Hryvnia ukrainienne' },
  UYU: { symbol: '$U', decimals: 2, label: 'Peso uruguayen' },
  UZS: { symbol: 'so\'m', decimals: 2, label: 'Sum ouzbek' },
  VES: { symbol: 'Bs.S', decimals: 2, label: 'Bolivar vénézuélien' },
  VND: { symbol: '₫', decimals: 0, label: 'Dong vietnamien' },
  VUV: { symbol: 'VT', decimals: 0, label: 'Vatu vanuatais' },
  WST: { symbol: 'WS$', decimals: 2, label: 'Tala samoan' },
  XCD: { symbol: 'EC$', decimals: 2, label: 'Dollar des Caraïbes orientales' },
  XPF: { symbol: 'CFP', decimals: 0, label: 'Franc CFP' },
  YER: { symbol: 'YR', decimals: 2, label: 'Rial yéménite' },
};

// Approximate reference rates to USD (for Super Admin MRR consolidation)
export const USD_REFERENCE_RATES: Record<string, number> = {
  USD: 1, EUR: 1.08, GBP: 1.27, AED: 0.27,
  XAF: 0.00167, XOF: 0.00167, NGN: 0.00065, GHS: 0.078, KES: 0.0078,
  ZAR: 0.054, EGP: 0.021, MAD: 0.1, DZD: 0.0074, ETB: 0.018,
  TZS: 0.00039, UGX: 0.00027, CDF: 0.00037, GNF: 0.00012, SLL: 0.00005,
  LRD: 0.005, RWF: 0.00078, BIF: 0.00035, MWK: 0.00058, ZMW: 0.037,
  ZWL: 0.012, MZN: 0.016, AOA: 0.0011, SDG: 0.0017, TND: 0.32, LYD: 0.21,
  MRU: 0.025, GMD: 0.016, CVE: 0.0098, KMF: 0.0022, SCR: 0.073,
  MUR: 0.022, STN: 0.044, DJF: 0.0056, SOS: 0.0017, SSP: 0.00077,
  ERN: 0.067, LSL: 0.054, SZL: 0.054, BWP: 0.074, NAD: 0.054, MGA: 0.00022, SHP: 1.27,
  AFN: 0.014, ALL: 0.011, AMD: 0.0025, ANG: 0.56, ARS: 0.00085, AUD: 0.65, AWG: 0.56, AZN: 0.59, BAM: 0.55, BBD: 0.5, BDT: 0.0084, BHD: 2.65, BMD: 1, BND: 0.74, BOB: 0.145, BRL: 0.17, BSD: 1, BTN: 0.012, BYN: 0.3, BZD: 0.5, CAD: 0.73, CHF: 1.12, CKD: 0.6, CLP: 0.0011, CNY: 0.14, COP: 0.00023, CRC: 0.0019, CUC: 1, CZK: 0.043, DKK: 0.145, DOP: 0.017, FJD: 0.44, FKP: 1.27, GEL: 0.36, GIP: 1.27, GTQ: 0.13, GYD: 0.0048, HKD: 0.128, HNL: 0.04, HTG: 0.0076, HUF: 0.0027, IDR: 0.000061, ILS: 0.27, INR: 0.012, IQD: 0.00076, IRR: 0.000024, ISK: 0.0072, JMD: 0.0064, JOD: 1.41, JPY: 0.0067, KGS: 0.0114, KHR: 0.00024, KPW: 0.0011, KRW: 0.00069, KWD: 3.25, KYD: 1.2, KZT: 0.0019, LAK: 0.000045, LBP: 0.000011, LKR: 0.0033, MDL: 0.055, MKD: 0.017, MMK: 0.00048, MNT: 0.00029, MOP: 0.124, MVR: 0.065, MXN: 0.049, MYR: 0.22, NIO: 0.027, NOK: 0.09, NPR: 0.0075, NZD: 0.6, OMR: 2.6, PAB: 1, PEN: 0.27, PGK: 0.24, PHP: 0.017, PKR: 0.0036, PLN: 0.25, PYG: 0.00013, QAR: 0.275, RON: 0.22, RSD: 0.0092, RUB: 0.011, SAR: 0.267, SBD: 0.12, SEK: 0.093, SGD: 0.74, SRD: 0.029, SYP: 0.000077, THB: 0.028, TJS: 0.091, TMT: 0.286, TOP: 0.42, TRY: 0.024, TTD: 0.147, TWD: 0.031, UAH: 0.024, UYU: 0.024, UZS: 0.000078, VES: 0.014, VND: 0.000039, VUV: 0.0083, WST: 0.36, XCD: 0.37, XPF: 0.0091, YER: 0.004, BGN: 0.552,
};

// BUG FIX: `new Date().toISOString().slice(0, 10)` was used all over the
// app (invoices, quotes, purchases, expenses, deliveries, and the
// accounting/reports date-range math) to get "today" or a date boundary
// as YYYY-MM-DD. toISOString() always converts to UTC first — so for
// anyone in a timezone AHEAD of UTC (which is most of this app's target
// market: Lagos/Accra are UTC+0 so unaffected, but Nairobi, Kampala,
// Dar es Salaam, Cairo, Dubai and the rest of East/Central Africa and the
// Middle East are UTC+1 to UTC+4), the UTC date can be a full day behind
// the user's actual local date for part of every day (midnight to
// UTC+offset each morning). A merchant opening shop at 7am in Nairobi
// (UTC+3) creating a new purchase order would silently get YESTERDAY's
// date pre-filled. localDateStr() reads the local Y/M/D components
// instead, so it always matches the date on the user's own wall clock.
export function localDateStr(date: Date = new Date()): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

export function formatMoney(amount: number, currency: string): string {
  const info = CURRENCIES[currency] ?? { symbol: currency, decimals: 2 };
  const value = Number(amount || 0);
  const sign = value < 0 ? '-' : '';
  const abs = Math.abs(value);
  const fixed = abs.toFixed(info.decimals);
  const [intPart, decPart] = fixed.split('.');
  // Manual ASCII-only grouping — avoids the Unicode narrow-no-break-space
  // that Intl/toLocaleString('fr-FR') uses, which isn't in jsPDF's default
  // font glyph set and was rendering as a stray "/" on printed invoices.
  const grouped = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, '.');
  const formatted = decPart ? `${grouped},${decPart}` : grouped;
  return `${sign}${formatted} ${info.symbol}`;
}

export function getCountry(code: string): CountryInfo | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export const CONTINENT_LABELS: Record<CountryInfo['continent'], string> = {
  Africa: 'Afrique',
  Asia: 'Asie',
  'Middle East': 'Moyen-Orient',
  Europe: 'Europe',
  'North America': 'Amérique du Nord',
  'Central America & Caribbean': 'Amérique centrale & Caraïbes',
  'South America': 'Amérique du Sud',
  Oceania: 'Océanie',
};

// Groups all countries by continent, in a stable display order (Africa
// first, since it's the product's historical/primary market), each group
// sorted alphabetically by name. Replaces the old hardcoded
// `!['AE','US','FR','GB'].includes(code)` split, which silently lumped
// every non-African country into a single "international" bucket and broke
// down as soon as more than those 4 extra countries existed.
export function groupCountriesByContinent(): { continent: CountryInfo['continent']; label: string; countries: CountryInfo[] }[] {
  const order: CountryInfo['continent'][] = [
    'Africa', 'Europe', 'Middle East', 'Asia', 'North America',
    'Central America & Caribbean', 'South America', 'Oceania',
  ];
  return order
    .map((continent) => ({
      continent,
      label: CONTINENT_LABELS[continent],
      countries: COUNTRIES.filter((c) => c.continent === continent).sort((a, b) => a.name.localeCompare(b.name)),
    }))
    .filter((g) => g.countries.length > 0);
}

export function convertToUSD(amount: number, currency: string): number {
  const rate = USD_REFERENCE_RATES[currency] ?? 1;
  return amount * rate;
}
